### ISSUE TITLE
BMessages in BMessages are not converted as they should

### ISSUE THREAD

**Issue by Paradoxianer** [Paradoxianer/XMLBMessage#1]
```
PDocument::allNodes = BMessage(0x0) {
                node[0] = BMessage('pcOT') {
```

will be output as

```
<BMessage type="BMessage" what="0">
    <Data name="PDocument::allNodes" type="BMessage">
        <BMessage type="BMessage" what="0">
            <Data name="node" type="BMessage">
```

while it should be

```
<BMessage name="PDocument::allNodes" type="BMessage" what="0">
        <BMessage name="node" type="BMessage" what="0">
```

**Comment by humdingerb** [comment]
I cannot see the output you pasted above. You have to use markdown and check the "Preview".

I misread what you wrote and pasted something into the comment that I now removed again to create a new issue... oops.

**Comment by Paradoxianer** [comment]
Updated the description

**Comment by Paradoxianer** [comment]
This should be fixed with https://github.com/Paradoxianer/XMLBMessage/commit/b67b61d0aa2631dd90edd4e3095a48986e96b42c
