### ISSUE TITLE
Add flag to show BMessage/XML

### ISSUE THREAD

**Issue by humdingerb** [Paradoxianer/XMLBMessage#2]
Would be nice to have a -s (--show) parameter that displays a BMessage/XML file, like "message" does for BMessage files already. xmlbmessage should recognize if the file is XML or BMessage on its own.

**Comment by Paradoxianer** [comment]
-v would be more intuitive as --verbose is used more often to have more output or?

**Comment by humdingerb** [comment]
I don't think so. "--verbose" normally means printing more details while processing. My idea with "--show" was to show the file (BMessage or XML) without processing/converting it.  
Hmm, it's maybe not _that_ interesting a feature, as there's still the normal "message" for BMessages and a simple "less" or something for XML. The convenience might be that you don't have to know if it's a BMessage or XML file and you can just do a "xmlbmessage -s file"...

**Comment by Paradoxianer** [comment]
then it would be more something like "print to screen" -p or something..

**Comment by Paradoxianer** [comment]
Added -s to as argument
