### ISSUE TITLE
Simplify usage

### ISSUE THREAD

**Issue by humdingerb** [Paradoxianer/XMLBMessage#3]
Instead of the usage
`xmlbmessage [--toMessage] [INPUT FILE] [OUTPUT FILE]`
the tool could autodetect the INPUT FILE and output the "other format":
`xmlbmessage [INPUT FILE] [OUTPUT FILE]`
The OUTPUT FILE can be optional, i.e. if it's not given, output to {input file}.xml or {input file}-without-xml-extension.

**Comment by Paradoxianer** [comment]
Specifiying the outputfile somehow doesnt work

**Comment by Paradoxianer** [comment]
Is fixed now
